import React, {useState} from 'react';
import styled from 'styled-components';
import Banner from '../component/Banner';
import SearchBar from '../component/SearchBar';
import FileDropIn from '../component/FildDropIn';
import InputField from '../component/InputField';
import InputFields from '../component/InputFields';
import CodeEditor from '../component/CodeEditor';
import Button from '../component/StyledButton';
import ToggleSwitch from '../component/ToggleSwitch';

import InputFieldsFake from '../component/InputFieldsFake';


const ToggleSwitchContainer = styled.div`
  display: flex;
  justify-content: flex-end;
  margin-right: 20px;
`;

const Visualization = () => {
  const [showCodeEditor, setShowCodeEditor] = useState(false);
  const [typeVar1, setTypeVar1] = useState("10");
  const [typeVar2, setTypeVar2] = useState("12");
  const [typeVar3, setTypeVar3] = useState("13");
  const [typeVar4, setTypeVar4] = useState("14");
  const [typeVar5, setTypeVar5] = useState("15");
  const [typeVar6, setTypeVar6] = useState("16");

  const createAndDownloadCSV = () => {
    const filename = 'visualization_params.csv';
    const values = [typeVar1, typeVar2, typeVar3, typeVar4, typeVar5, typeVar6];
    const headers = ["Variable1", "Variable2", "Variable3", "Variable4", "Variable5", "Variable6"];
    let csvContent = "data:text/csv;charset=utf-8,";

    // Add headers
    csvContent += headers.join(",") + "\r\n";

    // Add the values
    csvContent += values.join(",") + "\r\n";

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', filename);
    document.body.appendChild(link); // Required for FF

    link.click(); // This will download the CSV file
    document.body.removeChild(link); // Clean up
    filename = 'visualization_params.jl';

    const varNames = ["var1", "var2", "var3", "var4", "var5", "var6"];
    let juliaContent = "## Julia variable assignments generated by Visualization app\n";

    // Add the variable assignments
    varNames.forEach((name, index) => {
      juliaContent += `const ${name} = ${JSON.stringify(values[index])}\n`;
    });

    const blob = new Blob([juliaContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    document.body.appendChild(link);

    link.click(); // This will download the .jl file
    document.body.removeChild(link); // Clean up
    URL.revokeObjectURL(url); // Free up memory - Important when handling blobs
  }

  const handleValuesChange = (index, value) => {
    switch(index) {
      case "1": 
        setTypeVar1(value);
        break;
      case "2":
        setTypeVar2(value);
        break;
      case "3":
        setTypeVar3(value);
        break;
      case "4":
        setTypeVar4(value);
        break;
      case "5":
        setTypeVar5(value);
        break;
      case "6":
        setTypeVar6(value);
        break;
      default:
        console.warn(`Unhandled field index: ${index}`);
    }
  }


  return (
    <div className="visualization">
      <h1>Input your parameters to get a Visualisation 🧮</h1>
      <FileDropIn/>
      <ToggleSwitchContainer>
        <ToggleSwitch onSwitch={setShowCodeEditor} />
      </ToggleSwitchContainer>

      {showCodeEditor ? (
        <>
          <h2>Code Editor</h2>
          <CodeEditor 
  typeVar1={typeVar1} 
  typeVar2={typeVar2} 
  typeVar3={typeVar3} 
  typeVar4={typeVar4} 
  typeVar5={typeVar5} 
  typeVar6={typeVar6} 
/>
        </>
      ) : (
        <>
          <h2>Input Parameters for Material</h2>
          <InputFields onValuesChange={handleValuesChange} values={[typeVar1, typeVar2, typeVar3, typeVar4, typeVar5, typeVar6]} />
          <h2>Input Parameters for Run Configuration</h2>
          <InputFieldsFake/>
          <h2>Input Parameters for Geometry</h2>
          <InputFieldsFake/>
        </>
      )}
    <Button heading={"Start Visualization"} onClick={createAndDownloadCSV} />

    </div>
  );
};

export default Visualization;